# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98c39ecbfe68b1dbf8addbac5a4a7d493c8c2eeeee3821ef3ec8fda1df802cc80c33b5adb8a91adb72ca4bc619a5e1d9c6967a32ba3dbb0f891c80c5b05e3eb2

test:
  secret_key_base: a34c22e6080ba22ca004286d4a6a31d2a062a77eec8ea87d04f4409f71915a54aa978ef07e8f3fc6c710667913ddad32efd24654f6b6311a1229a0733373947b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
